-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  tenant_domains

CREATE TABLE IF NOT EXISTS tenant_domains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  domain VARCHAR(255) NOT NULL,
  domain_ci TEXT GENERATED ALWAYS AS (lower(domain)) STORED,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_tenant_domains UNIQUE (tenant_id, domain_ci)
);
